spring:
  datasource:
    url: jdbc:mysql://192.168.33.11:3306/user_center
    hikari:
      username: root
      password: wpscloud
      driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: user-center

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        namespace: 0dcf01c4-fdc7-483f-8af6-6afb09a15103
