server:
  port: 8040
spring:
  application:
    name: gateway

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    gateway:
      #      discovery:
      #        locator:
      #          # 让gateway通过服务发现组件找到其他微服务
      #          enabled: true
      #      routes:    gateway:
      ##      discovery:
      ##        locator:
      ##          # 让gateway通过服务发现组件找到其他微服务
      ##          enabled: true
      ##      routes:
      ##        #自定义路由谓词工厂
      ##        - id: after_route
      ##          uri: lb://content-center
      ##          predicates:
      ##            #时间格式必须按照以下格式，参考（注意idea编码集必须改为utf8）TimeBetweenRoutePredicateFactory#main
      ###            - TimeBetween=上午9:00, 下午5:00
      ##            - After=2030-01-20T17:42:47.789-07:00[America/Denver]
      #
      #      routes:
      #        - id: header_route
      #          uri: lb://content-center
      ##          predicates:
      ##              # 当且仅当带有名为X-Request-Id，并且值符合正则\d+的Header时，才会转发到用户微服务
      ##              # 如Header满足条件，则访问http://localhost:8040/** -> user-center/**
      ##              # eg. 访问http://localhost:8040/users/1 -> user-center/users/1
      ##            - Header=X-Request-Id, \d+
      #          predicates:
      #            # 当且仅当请求时的时间After配置的时间时，才会转发到用户微服务
      #            # 目前配置不会进该路由配置，所以返回404
      #            # 将时间改成 < now的时间，则访问localhost:8040/** -> content-center/**
      #            # eg. 访问http://localhost:8040/shares/1 -> content-center/users/1
      #            - After=2023-05-06T00:42:41.168703200+08:00[Asia/Shanghai]
      #

      routes:
        #        - id: header_route
        #          uri: lb://content-center
        #          predicates:
        #              # 当且仅当带有名为X-Request-Id，并且值符合正则\d+的Header时，才会转发到用户微服务
        #              # 如Header满足条件，则访问http://localhost:8040/** -> user-center/**
        #              # eg. 访问http://localhost:8040/users/1 -> user-center/users/1
        #            - Header=X-Request-Id, \d+
        #          predicates:
        # 当且仅当请求时的时间After配置的时间时，才会转发到用户微服务
        # 目前配置不会进该路由配置，所以返回404
        # 将时间改成 < now的时间，则访问localhost:8040/** -> content-center/**
        # eg. 访问http://localhost:8040/shares/1 -> content-center/users/1
        #            - After=2023-05-06T00:42:41.168703200+08:00[Asia/Shanghai]

        #自定义路由谓词工厂
        - id: after_route
          uri: lb://content-center
          predicates:
            #时间格式必须按照以下格式，参考（注意idea编码集必须改为utf8）TimeBetweenRoutePredicateFactory#main
            - TimeBetween=09:00, 17:00
          filters:
            #自定义过滤器工厂类PreLogGatewayFilterFactory，随意传两个参数a和b，a=config.getName()，b=config.getValue()
            - PreLog=a,b

management:
  endpoints:
    web:
      exposure:
        include: gateway
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

jwt:
  secret: 秘钥
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600